[pytest]
testpaths = tests
filterwarnings =
    ignore:CSR support in pyOpenSSL is deprecated:DeprecationWarning
    ignore:X509Extension support in pyOpenSSL is deprecated:DeprecationWarning
    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning